<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<RootNamespace>WPF_SP</RootNamespace>
		<AssemblyName>WPF_SP</AssemblyName>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\WPF_SP.Data\WPF_SP.Data.csproj" />
	</ItemGroup>

</Project>